modLoader="javafml"
loaderVersion="[43,)"
license="Academic Free License v3.0"

[[mods]]
modId="scb"
version="1.0"
displayName="Spiritual Come Back (SCB)"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="kyleabiel1"
description="Back for your things or your grave without taking too much risk with the Spirit form!"

[[dependencies.scb]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




