modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="scb"
version="1.5"
displayName="Spiritual Come Back (SCB)"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="kyleabiel1"
description="Spiritual Come Back is a mod that allows you to return for your loot or your grave without taking too much risk along the way with the Spirit form! "

[[dependencies.scb]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"


[[dependencies.scb]]
    modId="kleiders_custom_renderer"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.scb]]
    modId="kleidersplayerrenderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.scb]]
    modId="kleiders_custom_renderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

